import React from 'react';
import { motion } from 'motion/react';
import { ExternalLink, Download, Share2, FileText, Image as ImageIcon, Video, Link as LinkIcon } from 'lucide-react';
import { toast } from 'sonner';

interface Result {
  type: 'image' | 'video' | 'text' | 'link';
  title: string;
  content: string;
  thumbnail?: string;
  url?: string;
  platform?: string;
}

interface ResultPanelProps {
  results: Result[];
}

export default function ResultPanel({ results }: ResultPanelProps) {
  if (results.length === 0) return null;

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="mt-8 space-y-6"
    >
      <div className="flex items-center gap-3">
        <div className="p-2 bg-cyan-500/10 rounded-lg">
          <FileText size={18} className="text-cyan-400" />
        </div>
        <h3 className="text-lg font-bold">Execution Results</h3>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {results.map((result, idx) => (
          <motion.div
            key={idx}
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ delay: idx * 0.1 }}
            className="bg-[#0a0a0a] border border-white/5 rounded-2xl overflow-hidden group hover:border-cyan-500/30 transition-all"
          >
            {result.thumbnail && (
              <div className="aspect-video relative overflow-hidden bg-zinc-900">
                <img 
                  src={result.thumbnail} 
                  alt={result.title} 
                  className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
                  referrerPolicy="no-referrer"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent" />
                <div className="absolute bottom-4 left-4">
                  {result.type === 'image' && <ImageIcon size={20} className="text-white" />}
                  {result.type === 'video' && <Video size={20} className="text-white" />}
                  {result.type === 'link' && <LinkIcon size={20} className="text-white" />}
                </div>
              </div>
            )}

            <div className="p-6">
              <div className="flex items-start justify-between mb-2">
                <h4 className="font-bold text-sm">{result.title}</h4>
                <div className="flex gap-2">
                  {result.url && (
                    <a 
                      href={result.url} 
                      target="_blank" 
                      rel="noopener noreferrer"
                      className="p-2 bg-white/5 rounded-lg hover:bg-white/10 text-zinc-400 hover:text-white transition-all"
                    >
                      <ExternalLink size={14} />
                    </a>
                  )}
                  <button 
                    onClick={() => {
                      navigator.clipboard.writeText(result.url || result.content);
                      toast.success('Link copied to clipboard');
                    }}
                    className="p-2 bg-white/5 rounded-lg hover:bg-white/10 text-zinc-400 hover:text-white transition-all"
                  >
                    <Share2 size={14} />
                  </button>
                </div>
              </div>
              
              <p className="text-xs text-zinc-500 line-clamp-2 leading-relaxed">
                {result.content}
              </p>

              <div className="mt-6 pt-4 border-t border-white/5 flex items-center justify-between">
                <span className="text-[10px] font-bold text-cyan-500 uppercase tracking-widest">
                  {result.platform ? `Generated via ${result.platform}` : 'Generated by S+ AI'}
                </span>
                <button 
                  onClick={() => toast.info('Download started...')}
                  className="flex items-center gap-1.5 text-[10px] font-bold text-zinc-400 hover:text-white uppercase tracking-widest transition-colors"
                >
                  <Download size={12} />
                  Download
                </button>
              </div>
            </div>
          </motion.div>
        ))}
      </div>
    </motion.div>
  );
}
